export const ICON_INPUT =[
    {
        value:'solar:alarm-add-bold'
    },{
        value:'solar:rocket-2-bold'
    },{
        value:'solar:shop-2-bold'
    },{
        value:'solar:gameboy-bold'
    },{
        value:'solar:gamepad-bold'
    },{
        value:'solar:folder-with-files-bold'
    },{
        value:'solar:home-wifi-angle-bold'
    },{
        value:'solar:server-square-cloud-bold'
    },{
        value:'solar:video-frame-play-vertical-bold'
    },{
        value:'solar:settings-bold'
    },{
        value:'solar:add-circle-broken'
    },{
        value:'solar:clipboard-list-bold'
    },{
        value:'solar:link-square-bold'
    },{
        value:'solar:bicycling-bold'
    },{
        value:'solar:armchair-2-bold'
    },{
        value:'solar:telescope-bold'
    },{
        value:'solar:pallete-2-bold'
    },{
        value:'solar:donut-bitten-bold'
    }
]