export const COLOR_INPUT =[
    {
        value:'#B4DE60'
    },{
        value:'#FF9500'
    },{
        value:'#EDBE00'
    },{
        value:'#77CC00'
    },{
        value:'#14D9BF'
    },{
        value:'#007AFF'
    },{
        value:'#F64646'
    },{
        value:'#FF37AA'
    },{
        value:'#A100FF'
    },{
        value:'#FFC36F'
    },{
        value:'#5B676F'
    },{
        value:'#DE60B4'
    }
]